### ISSUE TITLE
anyone using faye-websockets with koa?

### ISSUE THREAD

**Issue by Karl01** [faye/faye-websocket-node#43]
websocket newbie, maybe someone has the answer whilst I'mreading more code examples:

am doing this on the server (coffeescript, apologies in advance)

server.on 'upgrade', (request, socket, body) ->
  if WebSocket.isWebSocket(request)
    co(->
       redisStore = new RedisStore() #from require('koa-redis')
           sessionId = '' + request.headers.cookie.slice(9,request.headers.cookie.indexOf(";"))
           sessionData = yield redisStore.get(sessionId) #works fine here, get and set ...

       if sessionData.LoginUser? and sessionData.LoginUser > 0
          loginUser = sessionData.LoginUser + ''
          ws = new WebSocket(request, socket, body)
          .... # on open ... on error...
          ws.on 'message', (event) ->
              msgData = JSON.parse(event.data) 
              ...
              #all including pushing into an array works fine 
              #but I can't 'yield' anything here. Where am I thinking wrong?
              yield redisStore.set("mytest","data of mytest",60 * 60 * 12 * 1000)

Thanks

**Comment by jcoglan** [comment]
I'm no expert on `co` but I think this is not working because your second `yield` is not part of the co-function, it's part of a function nested inside of the co-function. `yield` will only work from call sites that are part of the co-function.

There's also a syntax error; the `(` in `co(->` is unmatched, and if you write it as `co ->` this doesn't produce a generator, which is what you have to use to make `yield` work.

**Comment by Karl01** [comment]
Thanks, James, that was it, how dumb of me, the second co(...), (forgot the ').catch(anyOtherError)' at the end of the snippet above), Happy Easter holidays and thanks for a great module
