### ISSUE TITLE
close API call

### ISSUE THREAD

**Issue by orodeh** [faye/faye-websocket-node#44]
Hello,
   At DNAnexus Inc., we are using the close API call. It used to take a code and reason arguments. This worked for us in version 0.4.3, but stopped working in 0.9.4. From reading the code, it looks like the api.js implementation of close() takes no arguments (v0.9.4). How can we fix this? 

  Thanks,
      Ohad.

PS
  I finally fixed this, by patching the code. The file I changed was libs/faye/api.js, lines 95-100, the close function call. The new code is:

  close: function(status, reason, ack) {
    //this._closeParams = [reason, status];
    if (this.readyState !== API.CLOSED) this.readyState = API.CLOSING;
    this._driver.close(reason, status);
  },

**Comment by jcoglan** [comment]
This is fixed in https://github.com/faye/faye-websocket-node/commit/8460dd9f03207822775b8a0f8211e56f2e1fccb8.

I think I must have referred to an outdated version of the API spec when I remove these in 0.5, or it was an oversight when I was refactoring everything to extract websocket-driver, or possibly I checked in a browser at the time and it seemed not to implement these parameters.
