### ISSUE TITLE
Close code limits are too restrictive

### ISSUE THREAD

**Issue by brycekahle** [faye/faye-websocket-node#46]
According to the [protocol](https://tools.ietf.org/html/rfc6455#section-7.4.1), there are many valid close codes other than 1000 and 3000-4999. The current limits imposed at https://github.com/faye/faye-websocket-node/blob/854c0a96581d95d0f07db01ce48431a4098e7c60/lib/faye/websocket/api.js#L99 seem too restrictive.

**Comment by jcoglan** [comment]
They are the same limits imposed by browsers (at least by Chrome, if I recall), which is what this library is intended to emulate. The codes in the range 1001 to 1011 are for use by the protocol and should not need to be set by users; all circumstances in which they should be used should dealt with by `websocket-driver`.

Which code(s) do you want to use, and what's your use case?

**Comment by brycekahle** [comment]
I'm using this in the server context, not the client. See https://github.com/sockjs/sockjs-node/blob/master/src/trans-websocket.coffee#L71

**Comment by jcoglan** [comment]
I believe those error codes are reserved for use by the protocol itself, and 3000 to 4999 are for use by applications. ("Application" meaning anything built on top of WebSocket, I assume.) 1002 indicates a protocol error *in the WebSocket frames*, not in the application protocol being transported by the socket. 

A peer receiving well-formed WebSocket frames should not emit a 1002, and a well-behaving peer should not expect to receive one; a 1002 indicates a bug in the WebSocket library itself rather than in the application.

In an application, it would be just as valid for a client-side socket to emit an error because it received invalid JSON, but the browser will not let such a socket send a 1002. This is not a client-side/server-side distinction, it's a distinction between the WebSocket protocol and application protocols transported by it.
